[mcp_servers.context7]
command = "npx"
args = [
    "-y",
    "@upstash/context7-mcp",
]

[mcp_servers.kubernetes]
command = "npx"
args = [
    "-y",
    "kubernetes-mcp-server@latest",
    "--disable-multi-cluster",
]
